### ISSUE TITLE
hotfix/login-loginController

### ISSUE THREAD

**Issue by recepcanfa** [serbayacar/GitBootcamp#1]
LoginController.php ---> line number 2 --> 0R - o yerine sıfır yazılmış.

LoginController.php ---> line number 3 --> controller controller dan  extend edilmeli.

index fonksiyonunda _head ve _footer satırı silinmesi lazım
index fonksiyonunda login.html yerine login yazmalı

**Comment by furkanonder** [comment]
hepsi düzeltildi
