### ISSUE TITLE
hotfix/post - post ekranı hatası 

### ISSUE THREAD

**Issue by recepcanfa** [serbayacar/GitBootcamp#3]
Post_Controller.php ---> Line 2 --> OR O yerine sıfır yazılmış.
CSS'ler gelmiyor.CSS dosyaları CodeIgniter kurallarına göre ilgili klasörde olmalı ve oradan import edilmeli.

**Comment by furkanonder** [comment]
Post_Controller.php ---> Line 2 --> OR O yerine sıfır yazılmış. hatası düzeltildi

**Comment by aysedemirel** [comment]
CSS dosyaları CodeIgniter kurallarına göre ilgili klasöre taşındı ve oradan import edildi.
