### ISSUE TITLE
hotfix/Post - PostGirdi_Controller

### ISSUE THREAD

**Issue by recepcanfa** [serbayacar/GitBootcamp#4]
Line number 16 ----> input>-post ---> input->post olmalı
Line number 16 ----> post("selectKategori")

post.html  ve postGirdi.html ----> *.php olmalı

CSS yüklenmiyor. CodeIgniter mantığı ile yazılacak.

**Comment by nurates** [comment]
İlk 3 satırdaki hatalar düzeltildi.

**Comment by serbayacar** [comment]
AyseDemirel ilgili branchte hatayı düzeltmiştir.
